services:
  backend:
    image: maven:3.9.4-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./backend/cloud:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      - db
